# ndarray 형태변경
- `reshape()`: 원소 개수는 유지하고 배열 모양만 변경함
- `resize()`: 배열 크기 변경함, 원본 수정 가능함
- `ravel()`: 다차원 배열을 1차원으로 펼침
- `expand_dims()`: 지정 axis에 새 차원 추가함
- `squeeze()`: 크기가 1인 차원 제거함
- `transpose()`: 배열 축을 전치함
- `swapaxes()`: 두 축을 서로 교환함
- `rollaxis()`: 지정 축 위치를 이동함
- `moveaxis()`: 축 순서를 변경함
- `broadcast_to()`: 배열을 지정 shape로 broadcast함
- `broadcast_arrays()`: 여러 배열을 broadcast 가능한 형태로 맞춤
- `concatenate()`: 배열 연결함
- `stack()`: 새 축을 만들며 배열을 쌓음
- `hstack()`: 가로 방향으로 배열을 쌓음
- `vstack()`: 세로 방향으로 배열을 쌓음
- `dstack()`: 깊이 방향으로 배열을 쌓음
- `split()`: 배열을 나눔
- `hsplit()`: 가로 방향으로 배열을 나눔
- `vsplit()`: 세로 방향으로 배열을 나눔
- `dsplit()`: 깊이 방향으로 배열을 나눔
- `tile()`: 배열을 반복 배치함
- `repeat()`: 배열 원소를 반복함
- `unique()`: 중복 제거 후 고유값 반환함
- `flip()`: 배열 원소 순서를 뒤집음
- `fliplr()`: 좌우 방향으로 뒤집음
- `flipud()`: 상하 방향으로 뒤집음
- `roll()`: 배열 원소를 순환 이동함
- `rot90()`: 배열을 90도 회전함


In [1]:
import numpy as np

In [7]:
# reshape() : 지정된 배열의 차원(모양) 변경
# -1 : 남은 차원의 수를 Numpy에게 자동 계산하라고 지시

arr = np.arange(12) # 0~ 11
# arr.reshape((3,4))
# arr.reshape(3,-1) # 3행으로 만들라고 지시, 열의 개수는 알아서 계신
# arr.reshape(5,-1) # 행의 개수는 전체 size의 약수로만 지정해야 함
arr.reshape(-1,4) # 열은 4개, 행은 자동계신
# arr.reshape(-1,-1) # 당연히 안 됨


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
# ravel(): 다차원 배열을 1차원 배열로 변환
# [중요] : ravel()의 결과 1차언 배열은 원본과 값을 공유한다 (얕은 복사)
arr = np.random.randint(1, 10, (3,4))
flat = np.ravel(arr) # 2차원 배열이 1차원으로 편평하게 변함
print(arr)
print()
print(flat)

[[3 2 1 5]
 [3 4 6 9]
 [3 7 9 4]]

[3 2 1 5 3 4 6 9 3 7 9 4]


In [13]:
# ravel() 결과의 값을 수정(값 공유 확인)
flat[0] = 100
print(arr)
print()
print(flat)

[[100   2   1   5]
 [  3   4   6   9]
 [  3   7   9   4]]

[100   2   1   5   3   4   6   9   3   7   9   4]


In [ ]:
# 깊은 복사본이 필요하면 flatten() 을 사용함
