In [1]:
import numpy as np

NumPy를 사용하여 다음과 같은 배열을 생성해 보세요.

1. 크기가 4x3인 모든 값이 0인 배열
2. 크기가 3x3인 모든 값이 1인 배열
3. 0에서 20까지 5씩 증가하는 값으로 구성된 배열
4. 0과 1 사이의 4개의 등간격 값을 가진 배열
5. *크기가 2x2인 정규 분포로 구성된 배열*

In [13]:
print(np.zeros([4,3]))
print(np.ones([3,3]))
print(np.arange(0,21,5))
print(np.linspace(0,1,4))
print(np.random.normal(4,1,(2,2)))


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[ 0  5 10 15 20]
[0.         0.33333333 0.66666667 1.        ]
[[3.25195904 5.38251272]
 [4.8147478  2.0163173 ]]


1. 배열 `arr`에서 1번째 열만 추출
2. 배열 `arr`에서 1번째 행, 2번째 열의 값을 출력
3. 배열 `arr`에서 첫 번째 행부터 두 번째 행까지 선택하고, 0번째와 1번째 열만 추출



In [26]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr)
print()
print(arr[:, 0])
print()
print(arr[0,1])
print()
print(arr[:2,:2])

[[10 20 30]
 [40 50 60]
 [70 80 90]]

[10 40 70]

20

[[10 20]
 [40 50]]


[실습 2] 팬시 인덱싱과 불리언 인덱싱

아래 배열에서 팬시 인덱싱과 불리언 인덱싱을 사용하여 다음 작업을 수행하세요.

1. 팬시 인덱싱을 사용하여 배열의 0번째, 2번째, 4번째 요소를 출력
2. 배열의 값 중 50보다 큰 값만 추출

In [28]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(arr[0], arr[2], arr[4])
print(arr[arr > 50])

10 30 50
[60 70]


어느 마트에서 판매되는 제품들의 월별 매출량이 아래와 같이 주어졌습니다. 각각의 행은 제품을 나타내고, 열은 각 월의 판매량을 나타냅니다.

1. 월별 판매량이 200개 이상인 제품의 판매량을 선택하라.
2. 3월(세 번째 열)의 판매량이 100개 이하인 제품의 1월과 2월 판매량을 추출하라.
3. 2월(두 번째 열)의 판매량이 150개 이상인 제품들의 전체 월별 판매량을 출력하라.

In [49]:
sales = np.array([[120, 150, 100],
                  [80, 90, 110],
                  [200, 180, 220],
                  [50, 45, 70],
                  [300, 320, 310]])

print(sales[sales > 200])

sales_2 = sales[:,2]
print(sales_2[sales_2 <= 100])
print(sales[0,:2], sales[3,:2])

sales_3 = sales[:,1]
print(sales_3[sales_3 >= 150])
print(sales[::2,:])



[220 300 320 310]
[100  70]
[120 150] [50 45]
[150 180 320]
[[120 150 100]
 [200 180 220]
 [300 320 310]]


다음과 같은 과일 판매량 데이터가 있습니다. 각 과일의 1분기와 2분기 판매량이 주어졌을 때, NumPy 배열을 사용하여 아래 문제를 해결하세요.

1. 1분기와 2분기의 과일별 총 판매량을 구하세요.
2. 과일별 평균 판매량을 구하세요.

- **데이터**:
    - 1분기 판매량: `[200, 340, 150, 400]` (사과, 배, 오렌지, 바나나)
    - 2분기 판매량: `[220, 300, 180, 420]` (사과, 배, 오렌지, 바나나)

In [67]:
q_1 = np.array([200,340,150,400])
q_2 = np.array([220,300,180,420])

q = q_1 + q_2
print(q)

for i in range(0,4):
    avg = (q_1[i] + q_2[i]) /2
    print(avg)

[420 640 330 820]
210.0
320.0
165.0
410.0


다음 두 배열을 사용하여 각각의 요소별로 덧셈, 뺄셈, 곱셈, 나눗셈을 수행하세요.

In [69]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


아래의 2차원 배열과 1차원 배열을 브로드캐스팅하여 더하세요.

In [71]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])
arr1d = np.array([10, 20, 30])

print(arr2d + arr1d)

[[11 22 33]
 [14 25 36]]


1. 배열에서 20보다 큰 값을 찾아 출력하세요.
2. 배열의 합계, 최대값, 최소값, 평균을 계산하세요.

In [75]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[arr>20])

print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))

[30 40 50]
150
50
10
30.0


아래 배열에서 평균, 중앙값, 최빈값, 분산, 표준편차, 범위를 계산하세요.

In [80]:
arr = np.array([10, 20, 30, 30, 40, 50, 60])


print(np.mean(arr))
print(np.median(arr))
print(np.unique(arr))
print(np.var(arr))
print(np.std(arr))
# 범위?



34.285714285714285
30.0
[10 20 30 40 50 60]
253.06122448979593
15.90789817951435


정규분포와 균등분포에서 각각 난수를 생성하여, 평균과 표준편차를 계산하세요.

1. 평균 0, 표준편차 1인 정규분포 난수 1000개 생성
2. 0과 1 사이의 균등분포 난수 1000개 생성

In [82]:
print(np.random.normal(0,1,1000))

print(np.random.rand(1000))

[-0.39027133  1.14002068  1.02845579  1.06372294  0.30673524  0.54613381
  0.5244349  -0.11787437 -0.22950496 -0.39218861 -0.48767529 -0.85589648
 -0.09713883 -0.09673512 -0.82373092 -0.72887748  1.67703786 -0.5663144
  0.31530883 -0.38792343 -1.90039849  0.71415226  1.25714708  1.12491322
  0.59349252 -0.34898615 -0.86960182  0.62746188 -2.67740806 -1.2962077
  0.23555597  0.7309834  -0.79272702  0.30514646  1.68936638  0.45706235
  0.79607044 -0.38287809 -1.43015314 -2.72796991 -0.55114419  0.93710665
 -0.35348699 -0.61608963  1.44647828  0.34216453 -0.37290327  1.13972795
  1.05967461  1.1574198  -0.29294555 -2.51656078  0.56996263 -0.57287425
 -0.16017435  0.71811663 -0.30943386 -0.61436362 -1.12600715 -2.34782248
  0.44978214 -0.14462228  1.02902954 -1.32902884 -0.289245    0.55499049
  0.40640155  0.66002166 -0.76657665 -0.77184471  0.23450309 -1.03139683
  0.26553186 -1.40620045  0.39448485  1.59948291 -1.48423909 -1.79789889
 -1.90636504  0.07425876  0.75223686 -0.10185468 -0.7

아래와 같이 학생별 과목 성적 데이터가 주어졌을 때, 각 학생의 전체 평균 성적(수학, 영어, 과학)을 계산한 후, 이 평균값에 대한 분산과 표준편차를 구하세요.